### PR TITLE
fix: avoid overwriting the configuration file environment variable

### LINKED ISSUE #140: Bug report: Using the `--config` flag changes the `WD_CONFIG` environment variable
**Describe the bug**

The `WD_CONFIG` environment variable is changed after using the `--config` flag.

**To reproduce**

1. List outputs from the current `WD_CONFIG` value. This could be using a default that might have a few points included:

```zsh
$ echo $WD_CONFIG
/home/user/.warprc
$ cat $WD_CONFIG
...
$ wd list
...
```

2. List points from a configuration that might not exist. This might list nothing:

```zsh
$ wd --config /tmp/points list
...
```

3. Attempt to list points from the earlier `WD_CONFIG` value without using a flag:

```zsh
$ wd list
...
$ echo $WD_CONFIG
/tmp/points
```

**Current behavior**

The last commands lists values from flagged `--config` options from a previous command.

**Expected behavior**

The last commands to list the values from the initial `WD_CONFIG` variable since no flag is provided.

**Desktop**

- zsh version: `5.9`
- wd version: `0.9.1`

**Additional context**

I'm unsure if this should be an issue or if this flag is meant to change the `WD_CONFIG` value overall. Though no problem closing this if it's expected!

### PR DESCRIPTION
**Pull request by zimeg**
### Summary

:wave: Hello! This PR restores the initial value of the `WD_CONFIG` environment variable after the `--config` flag is used. It hopes to fix #140.

Also included is an update to `source` the tested `wd` so changed variables and directories are shared between different testing commands.

### Preview

The following steps have commands that use different configuration files, but the last commands use a configuration from the option above which might be an unexpected part!

#### Example

1. List outputs from the current `WD_CONFIG` value. This could be using a default that might have a few points included:

```zsh
$ echo $WD_CONFIG
/home/user/.warprc
$ cat $WD_CONFIG
...
$ wd list
...
```

2. List points from a configuration that might not exist. This might list nothing:

```zsh
$ wd --config /tmp/points list
...
```

3. Attempt to list points from the earlier `WD_CONFIG` value without using a flag:

```zsh
$ wd list
...
$ echo $WD_CONFIG
/tmp/points
```

### Reviewers

Use the last commit on this branch when installing via a package manager, or check out the branch and follow the steps below to test the example included above. If things are working, the value of the `WD_CONFIG` variable should match what it does in the first step 🙏 

#### Testing with a checked out files

For testing the changes of the files in this checked out branch, removing the `READONLY` from `wd.sh` before sourcing can be useful!

```diff
- readonly WD_VERSION=0.9.1
+ WD_VERSION=0.9.1
```

Changing `wd` to `./wd.sh` with the changes of this branch can also be used with the steps above for testing things:

```diff
- $ wd list
+ $ source ./wd.sh list
```

### Notes

The `wd_force_mode` variable is also unset as part of these changes, but this can of course be reverted!

### CODE REVIEW

File: test/tests.sh [hunk 1]
```diff
@@ -40,7 +40,7 @@ WD_PATH=${PWD}/..
 
 wd()
 {
-    "${WD_PATH}"/wd.sh "$@"
+    source "${WD_PATH}"/wd.sh "$@"
```
Comment (zimeg) [inline test/tests.sh:43]: 🏷️ Including just this change - nothing else to tests or `wd.sh` - will cause `test_config` to fail with:

```
test_config
ASSERT:expected:<0> but was:<1>
rm: cannot remove '/tmp/tmp.Qj3BlEu99M': No such file or directory
```

File: test/tests.sh [hunk 2]
```diff
@@ -498,7 +498,9 @@ test_config()
     wd -q --config "$arg_config" add
 
     assertEquals 1 "$(wcl < "$arg_config")"
-    assertEquals "$wd_config_lines" "$(total_wps)"
+    assertEquals "$wd_config_lines" "$(total_wps)" # $WD_CONFIG is unchanged
+    assertEquals "$wd_config_lines" 0
```
Comment (zimeg) [inline test/tests.sh:502]: 🏷️ No change to this part of the test, just a note with what's now being tested and `0` to make this part a little more clear!

**Review by zimeg — COMMENTED** [review]
📝 Leaving a few notes on changes to the tests in these comments!

**Review by alpha-tango-kilo — CHANGES_REQUESTED** [review]
I think my preference here would be to use a local variable to store the path of the wd config file being used this run, instead of using `WD_CONFIG` for that and then having `wd_config_initial` to restore the value afterwards

This would mean that the environment variable is never changed, even while the script is running, and keeps SCREAMING_SNAKE_CASE to mean a constant

What do you think? I'm hoping this won't be too difficult to implement

File: wd.sh [hunk 3]
```diff
@@ -442,16 +442,19 @@ then
...
 fi
 
+# set the config file from variable or default
+typeset wd_config_file=${WD_CONFIG:-$HOME/.warprc}
 if [[ ! -z $wd_alt_config ]]
 then
-    WD_CONFIG=$wd_alt_config[2]
+    # prefer the flag if provided
+    wd_config_file=$wd_alt_config[2]
 fi
```
Comment (zimeg) [inline wd.sh:451]: 📝 Most changes in this file are focused around this new `wd_config_file` variable!

File: test/tests.sh (hunk 1 above)
Comment (zimeg) [reply test/tests.sh:43]: Also want to add that the default `WD_CONFIG` in tests seems to not affect the "outside" variable, so it's not changed!

**Review by zimeg — COMMENTED** [review]
@alpha-tango-kilo 🙏 Thank you for the review and suggestion!

I agree that it's more clear to use a local variable here and this seems to work well when replaced throughout the `wd.sh` script 🔍 

Setting an initial value for `WD_CONFIG` [was kept](https://github.com/zimeg/wd/blob/88fd80a8a28af7f1a9df016249f702c6b9d2d917/wd.sh#L426) to avoid a breaking changes, but it does mean `WD_CONFIG` is written after a run. I think keeping it might be useful for some odd scripts, but let me know if it should be removed!

Also let me know if other changes should be made. In the meantime I'll rebase #143 with these changes 🚀
