### PR TITLE
fix: set the exit code to the return of cd for the warp function

### LINKED ISSUE #142: Bug report: The exit code remains `0` if a nested directory does not exist
**Describe the bug**

The exit code remains `0` if the nested directory of a warp point doesn't exit and the current path remains the same.

In this example the `setup.sh` script is run when it can't be found in the current directory:

```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:18: no such file or directory: /home/user/unknown
zsh: no such file or directory: ./setup.sh
```

**To reproduce**

1. Attempt to warp to unknown nested warp points:

```zsh
$ cd
$ wd add home
$ wd home unknown
wd_warp:cd:18: no such file or directory: /home/user/unknown
$ echo $?
0
$ pwd
/home/user
```

**Expected behavior**

The exit code to exit with an error code if the nested directory doesn't exit to skip following steps in chained commands:

```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:18: no such file or directory: /home/user/unknown
```

**Desktop**

- zsh version: `5.9`
- wd version: `0.9.1`

### PR DESCRIPTION
**Pull request by zimeg**
### Summary

:wave: 🤠 This PR updates the exit code with the returned value from `cd` in the `wd_warp` function to fix #142 and break chained commands if nested directories don't exist.

### Preview

With this change the exit code is set to `1` when a missing nested warp point is provided:

```zsh
$ wd home unknown
wd_warp:cd:19: no such file or directory: /home/user/unknown
$ echo $?
1
```

Chained commands also break once the missing nested warp point is reached:

```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:19: no such file or directory: /home/user/unknown
```

### Reviewers

To test the changes with this branch checked out, the following commands might be useful ✨ 

1. Attempt to warp to unknown nested warp points:

```zsh
$ cd
$ wd add home
$ wd home unknown
wd_warp:cd:19: no such file or directory: /home/user/unknown
$ echo $?
1
$ pwd
/home/user
```

### Notes

This change includes extra commits from #140 for some of the changes to testing. Please let me know if a rebase or other reverts are needed, or another change!

### CODE REVIEW

**Review by alpha-tango-kilo — APPROVED** [review]
This looks good. If you separate it from #140 I'll merge it now, or alternatively feel free to go through my feedback on #140 and then rebase this PR, whichever is easiest for you

File: wd.sh [hunk 1]
```diff
@@ -145,14 +145,17 @@ wd_warp()
...
         fi
     elif [[ ${points[$point]} != "" ]]
     then
         if [[ $sub != "" ]]
         then
             cd ${points[$point]/#\~/$HOME}/$sub
+            WD_EXIT_CODE=$?
         else
             cd ${points[$point]/#\~/$HOME}
+            WD_EXIT_CODE=$?
```
Comment (zimeg) [inline wd.sh:158]: This is the only change in this file related to this PR - the rest are #141 🔍

File: test/tests.sh [hunk 2]
```diff
@@ -497,8 +533,13 @@ test_config()
...
     wd -q --config "$arg_config" add
 
-    assertEquals 1 "$(wcl < "$arg_config")"
+    # confirm $WD_CONFIG was unchanged
     assertEquals "$wd_config_lines" "$(total_wps)"
+    assertEquals "$wd_config_lines" 0
+
+    # confirm --config was changed
+    assertEquals 1 "$(wcl < "$arg_config")"
+    assertEquals 1 "$(WD_CONFIG=$arg_config total_wps)"
```
Comment (zimeg) [inline test/tests.sh:542]: No changes to the asserts in this PR or the linked, but it's added for clarity as part of #141 🔬

**Review by zimeg — COMMENTED** [review]
@alpha-tango-kilo I just rebased it with the changes in #141 since these share a few testing changes needed for sourcing with `WD_CONFIG` 😅 

Thanks once more for the review, and please let me know if more updates are needed! 🙏 ✨

**Review by alpha-tango-kilo — APPROVED** [review]
Awesome, thanks!
